### ISSUE TITLE
Allow resetting

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#17]
Cannot reset the parameters to initial state. 

Can't seem to reset/realign points' n-dim orientation (if turned on when layer had changed orientation). Now the points are strangely "sunken" into the layers at a surreal angle.
__________________________________________________________
**Recommendation**

Allow user to reset to default individual parameters set per layer, or all at once (e.g. the sliders, dropdowns, etc). 

Determine if we should allow layers and points to change orientations independent of each other in the first place. If so, provide a way to reset both (points and layers') orientations.

Minor issue
●●○   Medium design work
▼▼▽   Medium development work

Should points keep their orientation when the layers have changed spatial orientation?
![pointiconorientation](https://user-images.githubusercontent.com/53277128/95919309-37db3100-0d62-11eb-8765-354b51685767.png)
![pointiconorientation2](https://user-images.githubusercontent.com/53277128/95919340-4295c600-0d62-11eb-8aee-0a99a5260413.png)

**Comment by goanpeca** [comment]
Would this be some sort of new button or context menu option @liaprins-czi ?

Is there some additional work/context needed before this can be tackled?

Thanks :)

**Comment by liaprins-czi** [comment]
Yes, I think we need more validation from people in community and / or users to verify if this is indeed something that should be changed, or if it is acting as expected. @sofroniewn do you have opinion on this one?

**Comment by sofroniewn** [comment]
The general concept of resetting the view is important. We have the "home" button in the bottom left that will reset the camera position, which would have brought these back in alignment.

I'm curious for this one @liaprins-czi did you try reseting the view with the home button (the little house)? Maybe it wasn't clear that is what it would do? It doesn't look like we expose that in the menubar right now either, though it does have a shortcut ... we might want to change that.

We also don't have an ability to reset the dims sliders, but that seems less critical to me too as it seems easier to move the sliders around.

We also don't have anyway to reset the colormaps or other layer properties/ drop downs. To me that falls more on the category of an undo rather than a reset though.

-----

Unfortunately, the crazy surreal angle of the points is harder to fix. It might not be impossible but it would be very challenging for us right now, deep in the weeds of the opengl shader code. The points layer is optimized for performance with many many points, and so doesn't have quite the flexibility that one might desire. I think it's locked in to all points having a fixed orientation independent of the camera view. We could flag for a vispy contractor if critical, it might be an easy fix for someone that knows how cc @justinelarsen.

**Comment by liaprins-czi** [comment]
Okay good to know @sofroniewn ; yes this issue is actually about a few things, and each of them seem to have a different solution
- resetting the view / angle: _home button_
- resetting the layer settings, i.e. blending modes): _undo_
- and also re-aligning the strangely angeled / sunken points: _not fixable / not worth fixing right now_

Maybe we can close this issue, then?

**Comment by sofroniewn** [comment]
> Maybe we can close this issue, then?

Yeah i'd be fine to close, maybe only thing I could thing of doing is adding the reset view to the menubar, but I guess it already has a button. I will close now, but we can reopen if people want to discuss further, have follow up ideas
