### ISSUE TITLE
Dropdown position

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#23]
Clicking a dropdown opens up the selections at the center of the list, rather than "dropping down" below the menu as traditionally seen in UI. This obstructs the view of other menu bars and controls.
__________________________________________________________
**Recommendation**
Menu items should expand and collapse below the control box.

Minor issue
●○○   Low design work
▼▽▽   Low development work

<img width="315" alt="dropdownpositioning" src="https://user-images.githubusercontent.com/53277128/95920800-f39d6000-0d64-11eb-99a0-c2b46cef0aaa.png">

**Comment by goanpeca** [comment]
>Clicking a dropdown opens up the selections at the center of the list, rather than "dropping down" below the menu as traditionally seen in UI. This obstructs the view of other menu bars and controls.

@liaprins-czi this is an issue that will be different on different operating systems, which also raises the question of *how much should we modify the default UX for a given system* to make them all uniform.

Qt aims to provide a native experience for every operating system, so this is the actual default behavior on OSX (however good or bad it may be)

<img width="654" alt="Screen Shot 2021-03-21 at 11 16 03 PM" src="https://user-images.githubusercontent.com/3627835/111939886-6987bf00-8a9b-11eb-8ffd-b5e9148a710a.png">

This will be different on Linux and Win as well. Do we really want to enforce a global behavior on all the operating systems?

Thoughts @napari/core-devs ?

---

This could be an interesting issue to work on @ppwadhwa . One way to do it is to recreate the "pop up" menu by creating a new [QMenu](https://doc.qt.io/qt-5/qmenu.html), populating it with the entries, and then making it appear on the desired position of the [QComboBox](https://doc.qt.io/qt-5/qcombobox.html#showPopup).

Unfortunately this cannot be accomplished by a 1 liner (like it would be on CSS), since the position of where the default pop up menu appears cannot be modified or configured on Qt.

**Comment by sofroniewn** [comment]
> Qt aims to provide a native experience for every operating system, so this is the actual default behavior on OSX (however good or bad it may be)
> 
> This will be different on Linux and Win as well. Do we really want to enforce a global behavior on all the operating systems?

Hmm, I'd probably be more inclined to stick with the default behaviour then. I'm a little wary of something too custom/ complex here.

Maybe theres another way to solve the problem instead though, like when we have more than 5 options instead of using a dropdown we use a line-edit search which shows the options similar to what you have typed. See this proposal from a while ago https://github.com/napari/napari/issues/268

**Comment by goanpeca** [comment]
My suggestion would be to not change this :). (maybe close the issue 🙃 )

**Comment by sofroniewn** [comment]
> My suggestion would be to not change this :). (maybe close the issue 🙃 )

Ok makes sense, but let's wait to hear from @liaprins-czi on this before deciding a next step

**Comment by justinelarsen** [comment]
I would agree with @goanpeca. At first glance, I understood why @liaprins-czi suggested this usability improvement, but testing out different dropdown menus on the mac, this is the default behavior that I never really paid attention to. I think keeping the default behavior of the OS as much as we can is the best for users and also easier maintenance for devs.

**Comment by liaprins-czi** [comment]
My bad! I agree we should keep it OS-dependent
