### ISSUE TITLE
Eraser tool bug

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#38]
Label layer eraser tool cannot make curved lines; does not follow where I drag it accurately.
__________________________________________________________
**Recommendation**

Fix so it follow the path of curser precisely.

Minor issue
○○○   No design work
▼▼▼   High development work

![eraser](https://user-images.githubusercontent.com/53277128/95918543-d8c8ec80-0d60-11eb-915a-05a5ab6c4a82.png)

**Comment by justinelarsen** [comment]
This could be because of linear interpolation and the overall refresh rate being slow. Speeding up the refresh rate could be the solution. See https://github.com/napari/napari/pull/713

**Comment by liu-ziyang** [comment]
unfortunately I can't quite relate https://github.com/napari/napari/pull/713 to this issue, do you have more context on how they are related? @jni / @sofroniewn?
I am also not able to reproduce this bug on my machine, I saw the refresh rate mentioned in the above comment, is it more likely to happen on a lower refresh rate monitor?

**Comment by jni** [comment]
@ziyangczi you need a large labels layer. Here's what happening:

- labels currently takes a long time to redraw, because there is expensive array computation done on the CPU, synchronously with rendering. That's because we need to convert labels (uint32 or similar) to a float32 in [0, 1] for VisPy, *and* we don't want the values to be sequential. All this will be improved with vispy/vispy#1912 and related PRs, but we're not there yet.
- when you are drawing on the labels layer, the above computation is happening on each redraw. This rate-limits the number of times the mouse can be polled for updates.
- in between updates, @sofroniewn implemented linear interpolation of the labels being updated. It *used* to be that all that stuff would not be painted over, and you'd get all these isolated spots! :facepalm: 

Does the above make sense? If you can't reproduce, you just need a bigger image and corresponding labels image. `data.eagle()` from skimage master is big enough on my laptop. This is me drawing little circles:

```python
import numpy as np
from skimage import data
import napari


image = data.eagle()  # about 2k x 2k
labels = np.zeros_like(image, dtype=np.uint32)

with napari.gui_qt():
    v = napari.Viewer()
    v.add_image(image)
    labels_layer = v.add_labels(labels)
    labels_layer.mode = 'paint'
```

![eagle-paint](https://user-images.githubusercontent.com/492549/97935836-54560200-1d3f-11eb-8104-332eb6e9eb19.png)

**Comment by liu-ziyang** [comment]
> Does the above make sense? If you can't reproduce, you just need a bigger image and corresponding labels image. `data.eagle()` from skimage master is big enough on my laptop. This is me drawing little circles:


ha! Thanks for the very detailed explanation! I will see what I can do about this

**Comment by liu-ziyang** [comment]
opened PR https://github.com/napari/napari/pull/1993 to collect feedback on the approach

**Comment by liu-ziyang** [comment]
opened another PR https://github.com/napari/napari/pull/2000 to try another approach

**Comment by psobolewskiPhD** [comment]
I cannot reproduce this on main 46dcc9c0976c35ec9dc64be60235f4addcadaa5c, perhaps due to:
https://github.com/napari/napari/pull/5732
